// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoncotesCountyLibraryAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library.Models.CheckoutDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("PatronId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CheckoutDays");
                });

            modelBuilder.Entity("Library.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Classical"
                        },
                        new
                        {
                            Id = 10,
                            Name = "News"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cooking"
                        });
                });

            modelBuilder.Entity("Library.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OutOfCirculationSince")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            MaterialName = "The Great Gatsby",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 1,
                            MaterialName = "To Kill a Mockingbird",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 2,
                            MaterialName = "The Hobbit",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 5,
                            MaterialName = "Dune",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 3,
                            MaterialName = "The Da Vinci Code",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 4,
                            MaterialName = "Steve Jobs",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 6,
                            MaterialName = "Abbey Road",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 7,
                            MaterialName = "Thriller",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 8,
                            MaterialName = "Kind of Blue",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 9,
                            MaterialName = "The Four Seasons",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 6,
                            MaterialName = "Nevermind",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 12,
                            MaterialName = "National Geographic - January 2024",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 10,
                            MaterialName = "Time Magazine - March 2024",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 11,
                            MaterialName = "Vogue - December 2023",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 13,
                            MaterialName = "Travel + Leisure - April 2024",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 14,
                            MaterialName = "Bon Appétit - February 2024",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Library.Models.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckoutDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckoutDays = 7,
                            Name = "Book"
                        },
                        new
                        {
                            Id = 2,
                            CheckoutDays = 5,
                            Name = "CD"
                        },
                        new
                        {
                            Id = 3,
                            CheckoutDays = 14,
                            Name = "Magazine"
                        });
                });

            modelBuilder.Entity("Library.Models.Patron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patron");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Email = "john.smith@gmail.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            Address = "342 Oh",
                            Email = "withers@gmail.com",
                            FirstName = "Bill",
                            IsActive = false,
                            LastName = "Withers"
                        },
                        new
                        {
                            Id = 3,
                            Address = "456 Oak Ave",
                            Email = "sarah.j@yahoo.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Address = "789 Pine Rd",
                            Email = "mbrown@hotmail.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            Address = "321 Elm St",
                            Email = "emily.davis@gmail.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 6,
                            Address = "654 Maple Dr",
                            Email = "rwilson@outlook.com",
                            FirstName = "Robert",
                            IsActive = false,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 7,
                            Address = "987 Cedar Ln",
                            Email = "jess.martinez@gmail.com",
                            FirstName = "Jessica",
                            IsActive = true,
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 8,
                            Address = "147 Birch Ct",
                            Email = "d.anderson@yahoo.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 9,
                            Address = "258 Spruce Way",
                            Email = "lisa.t@gmail.com",
                            FirstName = "Lisa",
                            IsActive = false,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 10,
                            Address = "369 Willow Blvd",
                            Email = "jthomas@hotmail.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Thomas"
                        });
                });

            modelBuilder.Entity("Library.Models.Material", b =>
                {
                    b.HasOne("Library.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Models.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MaterialType");
                });
#pragma warning restore 612, 618
        }
    }
}
